version: '3.6'

volumes:
  node_modules:  

services:
  app:
    platform: linux/x86_64
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3333:3333"
    user: 1000:1000
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    command: npm run dev