version: '3.6'

volumes:
  node_modules:  

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: "host"
    user: 1000:1000
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    command: npm run dev